---
version: '3'
services:

  ##Configure DB with Mysql
  logicea-mysql:
    container_name: logicea-mysql
    image: mysql:5.7
    volumes:
      - ./logicea-mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: logicea
      MYSQL_USER: root
      MYSQL_PASSWORD:

  ## back-end-service Docker Compose Config
  back-end-service:
    container_name: back-end-service
    image: iangithua/logicea-back-end-service:latest
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: cards_db
      DB_USER: root
      DB_PASSWORD:
    ports:
      - "8081:8080"
    depends_on:
      - logicea-mysql

  ## front-end-service Docker Compose Config
  front-end-service:
    container_name: front-end-service
    image: iangithua/logicea-front-end-service:latest
    depends_on:
      - back-end-service
    ports:
      - "8082:8080"
